# SPDX-License-Identifier: GPL-3.0-only
# Copyright (c) 2025 raspie10032

from .generators import NODE_CLASS_MAPPINGS as GENERATOR_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as GENERATOR_DISPLAY_MAPPINGS
from .converters import CONVERTER_NODE_CLASS_MAPPINGS, CONVERTER_NODE_DISPLAY_NAME_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **GENERATOR_MAPPINGS,
    **CONVERTER_NODE_CLASS_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **GENERATOR_DISPLAY_MAPPINGS,
    **CONVERTER_NODE_DISPLAY_NAME_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
